---
- name: install software-properties-common
  apt:
    name: software-properties-common
    
- name: add ansible repository
  apt_repository:
    repo: ppa:ansible/ansible
    state: present
    
- name: apt-get update
  apt:
    update_cache: yes

- name: install ansible
  apt:
    name: ansible=2.2*
