---
- hosts: test
  remote_user: deb # Logged in User
  become: true    # Change User , default root by sudo
  roles:
    - setup_db
    - setup_apache
    
- hosts: ansible
  remote_user: sk
  become: true
  roles:
    - setup_ansible