---
- name: install mysql
  apt: name=mysql-server state=present
  
- name: install libmysqlclient-dev
  apt: name=libmysqlclient-dev state=present
  
- name: intall python mysql connector
  pip: 
    name=MySQL-python
    version=1.2.5

- name: Add configuration
  template:
    src: my.cnf.j2
    dest: "/etc/mysql/my.cnf"
    owner: root
    group: root
    mode: 0644
    force: "true"
  notify: restart mysql

- name: Create database
  mysql_db:
    name: test
    state: present
    